### ISSUE TITLE
CameraPreviewView issue?

### ISSUE THREAD

**Issue by michaelprosario** [ollide/rosjava_android_template#1]
I'm trying to get the CameraPreviewView working following this blog post...

http://wiki.ros.org/ApplicationsPlatform/Clients/Android/Tutorials/Getting%20Started

My goal is to have the CameraPreviewView send phone camera data to my ROS server.

01-28 16:02:38.388 20762-20762/org.ollide.rosandroid D/ResourcesManager: creating new AssetManager and set to /data/app/org.ollide.rosandroid-1/base.apk
01-28 16:02:38.528 20762-20762/org.ollide.rosandroid D/Activity: performCreate Call secproduct feature valuefalse
01-28 16:02:38.528 20762-20762/org.ollide.rosandroid D/Activity: performCreate Call debug elastic valuetrue
01-28 16:02:38.608 20762-20794/org.ollide.rosandroid D/OpenGLRenderer: Render dirty regions requested: true
01-28 16:02:38.698 20762-20794/org.ollide.rosandroid I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
                                                                   OpenGL ES Shader Compiler Version: E031.25.03.06
                                                                   Build Date: 01/24/15 Sat
                                                                   Local Branch: AF11_RB1_AU15
                                                                   Remote Branch: 
                                                                   Local Patches: 
                                                                   Reconstruct Branch: 
01-28 16:02:38.698 20762-20794/org.ollide.rosandroid I/OpenGLRenderer: Initialized EGL, version 1.4
01-28 16:02:38.718 20762-20794/org.ollide.rosandroid D/OpenGLRenderer: Enabling debug mode 0
01-28 16:02:38.878 20762-20762/org.ollide.rosandroid I/Timeline: Timeline: Activity_launch_request id:org.ollide.rosandroid time:76181793
01-28 16:02:39.459 20762-20762/org.ollide.rosandroid D/Activity: performCreate Call secproduct feature valuefalse
01-28 16:02:39.459 20762-20762/org.ollide.rosandroid D/Activity: performCreate Call debug elastic valuetrue
01-28 16:02:39.519 20762-20762/org.ollide.rosandroid D/Activity: performCreate Call secproduct feature valuefalse
01-28 16:02:39.519 20762-20762/org.ollide.rosandroid D/Activity: performCreate Call debug elastic valuetrue
01-28 16:02:39.889 20762-20762/org.ollide.rosandroid I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@254b5514 time:76182804
01-28 16:02:39.889 20762-20762/org.ollide.rosandroid I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@254b5514 time:76182805
01-28 16:02:39.909 20762-20762/org.ollide.rosandroid V/ActivityThread: updateVisibility : ActivityRecord{2765dbe5 token=android.os.BinderProxy@3554a020 {org.ollide.rosandroid/org.ollide.rosandroid.MainActivity}} show : false
01-28 16:02:46.806 20762-20762/org.ollide.rosandroid D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
01-28 16:02:47.386 20762-20762/org.ollide.rosandroid W/CameraBase: An error occurred while connecting to camera: 0
01-28 16:02:47.386 20762-20762/org.ollide.rosandroid D/AndroidRuntime: Shutting down VM
01-28 16:02:47.396 20762-20762/org.ollide.rosandroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.ollide.rosandroid, PID: 20762
                                                                       java.lang.RuntimeException: Fail to connect to camera service
                                                                           at android.hardware.Camera.<init>(Camera.java:545)
                                                                           at android.hardware.Camera.open(Camera.java:385)
                                                                           at org.ollide.rosandroid.MainActivity$1.run(MainActivity.java:53)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

01-28 16:02:47.697 20762-21111/org.ollide.rosandroid I/Registrar: MasterXmlRpcEndpoint URI: http://192.168.0.66:11311/
01-28 16:02:47.807 20762-21156/org.ollide.rosandroid I/Registrar: Registering publisher: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</ros_camera_preview_view, http://192.168.0.65:50831/>, TopicIdentifier</rosout>>, Topic<TopicIdentifier</rosout>, TopicDescription<rosgraph_msgs/Log, acffd30cd6b6de30f120938c17c593fb>>>>
01-28 16:02:48.097 20762-21163/org.ollide.rosandroid I/Registrar: Response<Success, Registered [/ros_camera_preview_view] as publisher of [/rosout], [http://mrosario-ubuntu:44416/]>
01-28 16:02:48.097 20762-21159/org.ollide.rosandroid I/DefaultPublisher: Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</ros_camera_preview_view, http://192.168.0.65:50831/>, TopicIdentifier</rosout>>, Topic<TopicIdentifier</rosout>, TopicDescription<rosgraph_msgs/Log, acffd30cd6b6de30f120938c17c593fb>>>>
01-28 16:02:48.107 20762-21113/org.ollide.rosandroid I/Registrar: Registering publisher: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</ros_camera_preview_view, http://192.168.0.65:50831/>, TopicIdentifier</camera/image/compressed>>, Topic<TopicIdentifier</camera/image/compressed>, TopicDescription<sensor_msgs/CompressedImage, 8f7a12909da2c9d3332d540a0977563f>>>>
01-28 16:02:48.117 20762-21113/org.ollide.rosandroid I/Registrar: Registering publisher: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</ros_camera_preview_view, http://192.168.0.65:50831/>, TopicIdentifier</camera/camera_info>>, Topic<TopicIdentifier</camera/camera_info>, TopicDescription<sensor_msgs/CameraInfo, c9a58c1b0b154e0e6da7578cb991d214>>>>
01-28 16:02:48.137 20762-21175/org.ollide.rosandroid I/Registrar: Response<Success, Registered [/ros_camera_preview_view] as publisher of [/camera/image/compressed], []>
01-28 16:02:48.137 20762-21163/org.ollide.rosandroid I/DefaultPublisher: Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</ros_camera_preview_view, http://192.168.0.65:50831/>, TopicIdentifier</camera/image/compressed>>, Topic<TopicIdentifier</camera/image/compressed>, TopicDescription<sensor_msgs/CompressedImage, 8f7a12909da2c9d3332d540a0977563f>>>>
01-28 16:02:48.147 20762-21182/org.ollide.rosandroid I/Registrar: Response<Success, Registered [/ros_camera_preview_view] as publisher of [/camera/camera_info], []>
01-28 16:02:48.147 20762-21180/org.ollide.rosandroid I/DefaultPublisher: Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</ros_camera_preview_view, http://192.168.0.65:50831/>, TopicIdentifier</camera/camera_info>>, Topic<TopicIdentifier</camera/camera_info>, TopicDescription<sensor_msgs/CameraInfo, c9a58c1b0b154e0e6da7578cb991d214>>>>

Could I be missing a configuration setting somewhere?   

I appreciate any pointers that you might have.

All the best!

For your review... I have attached my manifest too.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.ollide.rosandroid" >

```
<application
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/AppTheme" >

    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />



    <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:screenOrientation="landscape"
        android:configChanges="orientation|keyboardHidden"


        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>



</application>
```

</manifest>

**Comment by michaelprosario** [comment]
Resolved issue.  I had my "uses-permission" elements in the wrong place in the manifest file.
