### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by mbdilaver** [ollide/rosjava_android_template#2]
Hi!
This is a really great work.
But I got a problem.
When I tap to the connect button in the first activity, the app crashes.
I wonder if you can help me.

OS: Windows 10
IDE: Android Studio 1.5
Device version: Android 5.0

Thanks

`FATAL EXCEPTION: pool-1-thread-7 Process: org.ollide.rosandroid, PID: 31466
                                                                       org.ros.exception.RosMessageRuntimeException: java.lang.ClassNotFoundException: Didn't find class "std_msgs.uint32" on path: DexPathList[[zip file "/data/app/org.ollide.rosandroid-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                           at org.ros.internal.message.definition.MessageDefinitionReflectionProvider.get(MessageDefinitionReflectionProvider.java:58)
                                                                           at org.ros.internal.message.Md5Generator.generate(Md5Generator.java:44)
                                                                           at org.ros.internal.message.Md5Generator$1.variableValue(Md5Generator.java:61)
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parseField(MessageDefinitionParser.java:172)
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parse(MessageDefinitionParser.java:107)
                                                                           at org.ros.internal.message.Md5Generator.generateText(Md5Generator.java:86)
                                                                           at org.ros.internal.message.Md5Generator.generate(Md5Generator.java:49)
                                                                           at org.ros.internal.message.Md5Generator$1.variableValue(Md5Generator.java:61)
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parseField(MessageDefinitionParser.java:172)
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parse(MessageDefinitionParser.java:107)
                                                                           at org.ros.internal.message.Md5Generator.generateText(Md5Generator.java:86)
                                                                           at org.ros.internal.message.Md5Generator.generate(Md5Generator.java:49)
                                                                           at org.ros.internal.message.topic.TopicDescriptionFactory.newFromType(TopicDescriptionFactory.java:36)
                                                                           at org.ros.internal.node.DefaultNode.newPublisher(DefaultNode.java:270)
                                                                           at org.ros.internal.node.RosoutLogger.<init>(RosoutLogger.java:41)
                                                                           at org.ros.internal.node.DefaultNode.start(DefaultNode.java:186)
                                                                           at org.ros.internal.node.DefaultNode.access$000(DefaultNode.java:85)
                                                                           at org.ros.internal.node.DefaultNode$1.run(DefaultNode.java:173)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "std_msgs.uint32" on path: DexPathList[[zip file "/data/app/org.ollide.rosandroid-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at org.ros.internal.message.definition.MessageDefinitionReflectionProvider.get(MessageDefinitionReflectionProvider.java:54)
                                                                           at org.ros.internal.message.Md5Generator.generate(Md5Generator.java:44) 
                                                                           at org.ros.internal.message.Md5Generator$1.variableValue(Md5Generator.java:61) 
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parseField(MessageDefinitionParser.java:172) 
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parse(MessageDefinitionParser.java:107) 
                                                                           at org.ros.internal.message.Md5Generator.generateText(Md5Generator.java:86) 
                                                                           at org.ros.internal.message.Md5Generator.generate(Md5Generator.java:49) 
                                                                           at org.ros.internal.message.Md5Generator$1.variableValue(Md5Generator.java:61) 
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parseField(MessageDefinitionParser.java:172) 
                                                                           at org.ros.internal.message.definition.MessageDefinitionParser.parse(MessageDefinitionParser.java:107) 
                                                                           at org.ros.internal.message.Md5Generator.generateText(Md5Generator.java:86) 
                                                                           at org.ros.internal.message.Md5Generator.generate(Md5Generator.java:49) 
                                                                           at org.ros.internal.message.topic.TopicDescriptionFactory.newFromType(TopicDescriptionFactory.java:36) 
                                                                           at org.ros.internal.node.DefaultNode.newPublisher(DefaultNode.java:270) 
                                                                           at org.ros.internal.node.RosoutLogger.<init>(RosoutLogger.java:41) 
                                                                           at org.ros.internal.node.DefaultNode.start(DefaultNode.java:186) 
                                                                           at org.ros.internal.node.DefaultNode.access$000(DefaultNode.java:85) 
                                                                           at org.ros.internal.node.DefaultNode$1.run(DefaultNode.java:173) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
                                                                        Suppressed: java.lang.ClassNotFoundException: std_msgs.uint32
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                ... 22 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by mbdilaver** [comment]
I solved the issue. I don't get this error on rooted devices so try with rooted devices.
http://answers.ros.org/question/232388/didnt-find-class-std_msgsuint32-error-on-android-studio-solved/
